name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Haddajii
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
